//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int Doctor_No { get; set; }
        public int Hospital_Cod { get; set; }
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
