//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Emp_No { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public Nullable<int> Dir { get; set; }
        public Nullable<System.DateTime> Fecha_Alt { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<int> Dept_No { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
