//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enfermo
    {
        public int Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Fecha_Nac { get; set; }
        public string S { get; set; }
        public Nullable<int> NSS { get; set; }
    }
}
